// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportClub.Data;

#nullable disable

namespace SportClub.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SportClub.Domain.CheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BarcodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckedInAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("ClientProfileId", "CheckedInAt")
                        .HasDatabaseName("IX_CheckIns_ClientProfile_Time");

                    b.ToTable("CheckIns", (string)null);
                });

            modelBuilder.Entity("SportClub.Domain.ClientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("IX_ClientProfiles_Barcode");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("IX_ClientProfiles_Phone");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ClientProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "SC-000001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBlocked = false,
                            IsDeleted = false,
                            Phone = "+380501234567",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("SportClub.Domain.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("DurationUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxVisits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Необмежені відвідування протягом 30 днів",
                            DurationUnit = "Months",
                            DurationValue = 1,
                            IsArchived = false,
                            Name = "Місячний безлімітний",
                            PlanType = "Unlimited",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "8 відвідувань, дійсний 60 днів",
                            DurationUnit = "Days",
                            DurationValue = 60,
                            IsArchived = false,
                            MaxVisits = 8,
                            Name = "8 занять",
                            PlanType = "LimitedVisits",
                            Price = 800m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "12 відвідувань, дійсний 90 днів",
                            DurationUnit = "Days",
                            DurationValue = 90,
                            IsArchived = false,
                            MaxVisits = 12,
                            Name = "12 занять",
                            PlanType = "LimitedVisits",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Необмежені відвідування протягом 3 місяців",
                            DurationUnit = "Months",
                            DurationValue = 3,
                            IsArchived = false,
                            Name = "Квартальний безлімітний",
                            PlanType = "Unlimited",
                            Price = 3000m
                        });
                });

            modelBuilder.Entity("SportClub.Domain.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActivationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FrozenDaysUsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FrozenSince")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("VisitsUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("PlanId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("SportClub.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@sportclub.ua",
                            FullName = "Адміністратор",
                            PasswordHash = "$2a$11$qcb/Xp9bOOGAtMPG3eHAjOyfUWMr/UFFqCbbcYsjI93Bfc7/R0ZZ6",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "reception@sportclub.ua",
                            FullName = "Рецепціоніст",
                            PasswordHash = "$2a$11$Ys2odVm45GEouw5Qf654reScCNYd7JvboX2.U.wvEiZm/2f0VIGiy",
                            Role = "Receptionist"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "client@sportclub.ua",
                            FullName = "Іван Петренко",
                            PasswordHash = "$2a$11$0W7fs1YtMQZN82.hvJTVIub0ZBiF0.kF/MMRjqeuc2YTEZfznvrp.",
                            Role = "Client"
                        });
                });

            modelBuilder.Entity("SportClub.Domain.CheckIn", b =>
                {
                    b.HasOne("SportClub.Domain.ClientProfile", "ClientProfile")
                        .WithMany("CheckIns")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportClub.Domain.Subscription", "Subscription")
                        .WithMany("CheckIns")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SportClub.Domain.ClientProfile", b =>
                {
                    b.HasOne("SportClub.Domain.User", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("SportClub.Domain.ClientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportClub.Domain.Subscription", b =>
                {
                    b.HasOne("SportClub.Domain.ClientProfile", "ClientProfile")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportClub.Domain.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SportClub.Domain.ClientProfile", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SportClub.Domain.Plan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SportClub.Domain.Subscription", b =>
                {
                    b.Navigation("CheckIns");
                });

            modelBuilder.Entity("SportClub.Domain.User", b =>
                {
                    b.Navigation("ClientProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
